name: Run Overcloud Database Backup

on:
  workflow_dispatch:
    inputs:
      kolla_tags:
        description: |
          The ansible tags to use when running kolla-ansible playbooks.
      kolla_limit:
        description: |
          The ansible limit to use for kolla-ansible playbooks.
      kayobe_limit:
        description: |
          The ansible limit to use when running kayobe playbooks.
      kayobe_tags:
        description: |
          The ansible tags to use when running kayobe playbooks.

jobs:
  prepare-runner:
    uses: ./.github/workflows/prepare-runner.yml
  run-overcloud-database-backup:
    runs-on: ['kayobe', 'openstack']
    permissions:
      contents: read
      packages: none
      pull-requests: none
    container:
      image: pulp.infra.os.hodgkiss.cloud/kayobe:${{ needs.prepare-runner.outputs.openstack_release }}-latest
      credentials:
        username: admin
        password: ${{ secrets.REGISTRY_PASSWORD }}
    concurrency:
      group: overcloud
      cancel-in-progress: false
    timeout-minutes: 360
    needs: prepare-runner
    steps:
      - name: Checkout kayobe config
        uses: actions/checkout@v3
        with:
          submodules: true
          path: kayobe-config

      - name: Symlink source checkout to expected location
        run: sudo ln -s $PWD/kayobe-config /src

      - name: Run overcloud database backup
        run: |
          /src/.automation/pipeline/overcloud-database-backup.sh
        env:
          KAYOBE_AUTOMATION_SSH_PRIVATE_KEY: "${{ secrets.KAYOBE_AUTOMATION_SSH_PRIVATE_KEY }}"
          KAYOBE_VAULT_PASSWORD: "${{ secrets.KAYOBE_VAULT_PASSWORD }}"
          KAYOBE_TAGS: '${{ github.event.inputs.kayobe_tags }}'
          KAYOBE_LIMIT: '${{ github.event.inputs.kayobe_limit }}'
          KOLLA_TAGS: '${{ github.event.inputs.kolla_tags }}'
          KOLLA_LIMIT: '${{ github.event.inputs.kolla_limit }}'
          HOME: '/stack'
